@hostname = localhost
@port = 5001
@host = {{hostname}}:{{port}}
@contentType = application/json

#GET https://{{host}}/meetings HTTP/1.1
#Accept: {{contentType}}


GET http://localhost:9000/v1.0/invoke/backend-service/method/WeatherForecast HTTP/1.1
#Accept: {{contentType}}