version: "3.8"

services:
  website:
    container_name: website
    image: esmann.azurecr.io/samples/web:latest
    build:
      context: ./src/web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - "redis-volume:/redis"
      - "website-volume:/dapr"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 1GB

  website-dapr:
    container_name: website-dapr
    image: "daprio/daprd:1.0.0-rc.1"
    command:
      [
        "./daprd",
        "-app-id",
        "website",
        "-app-port",
        "80",
        "-dapr-http-port",
        "3500",
        "-config",
        "/dapr/config.yaml",
        "-components-path",
        "/dapr",
      ]
    volumes:
      - "website-volume:/dapr"
    depends_on:
      - website
      - redis
    network_mode: "service:website"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 1GB

  api:
    container_name: api
    image: esmann.azurecr.io/samples/api:latest
    build:
      context: ./src/api
      dockerfile: Dockerfile
    expose:
      - 5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - "api-volume:/dapr"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 1GB

  api-dapr:
    container_name: api-dapr
    image: "daprio/daprd:1.0.0-rc.1"
    command:
      [
        "./daprd",
        "-app-id",
        "api",
        "-app-port",
        "5000",
        "-dapr-http-port",
        "3500",
        "-config",
        "/dapr/config.yaml",
        "-components-path",
        "/dapr",
      ]
    volumes:
      - "api-volume:/dapr"
    depends_on:
      - api
      - redis
    network_mode: "service:api"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 1GB

  ############################
  # Redis state store
  ############################
  redis:
    container_name: redis
    image: "redis:alpine"
    command: ["redis-server", "/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - "redis-volume:/redis"

  ############################
  # SQL Server 2019
  ############################
  db:
    container_name: db
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Qwerty12"
      ACCEPT_EULA: "Y"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 1GB

volumes:
  website-volume:
  api-volume:
  redis-volume:
