apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
  #namespace: default
spec:
  type: pubsub.redis
  metadata:
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: "S0m3P@$$w0rd"
