# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  api:
    image: api
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - 5000
    #ports:
    #  - "5001:5001"
    #  - "5000:5000"
    networks:
      - counter-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ~/.aspnet/https:/https:ro

  web:
    depends_on:
      - api
    image: web
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "443:5003"
      - "80:5002"
    networks:
      - counter-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5003;http://+:5002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
networks:
  counter-net:
