# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.7"

services:
  website:
    depends_on:
      - placement
      - redis
      - db
    image: web
    container_name: website
    build:
      context: ./src/web
      dockerfile: Dockerfile
    ports:
      - "443:5003"
      - "80:5002"
    networks:
      - counter-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5003;http://+:5002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  website_dapr:
    image: "daprio/daprd:0.10.0"
    command:
      [
        "./daprd",
        "-app-id",
        "website",
        "-app-port",
        "80",
        "-placement-address",
        "placement:6000",
        "-config",
        "/dapr/config.yaml",
        "-components-path",
        "/dapr/components",
      ]
    volumes:
      - "./components/local:/dapr/components"
      - "./components/config.yaml:/dapr/config.yaml"
      - ./vault_dev_token:/vault/token
    depends_on:
      - website
      - placement
    network_mode: "service:website"
    env_file:
      - .env

  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/placement:0.10.0"
    container_name: "placement"
    command: ["./placement", "-port", "6000"]
    ports:
      - "6000:6000"
    env_file:
      - .env
    networks:
      - counter-net

  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - counter-net

  ############################
  # SQL Server 2019
  ############################
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Qwerty12"
      ACCEPT_EULA: "Y"

networks:
  counter-net:
